name: londri
description: "An application to manage laundry business"
publish_to: "none"
version: 1.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  # Router
  go_router: ^14.8.0

  # Clean Architecture and BLoC
  flutter_bloc: ^9.0.0
  fpdart: ^1.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3

  # Supabase
  supabase_flutter: ^2.8.3

  # Dotenv
  flutter_dotenv: ^5.2.1

  # Google Fonts
  google_fonts: ^6.2.1

  # Localizations
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # UUID
  uuid: ^4.5.1

  # Timezone
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0

  # Autocomplete Field
  flutter_typeahead: ^5.2.0

  # Shared Preferences
  shared_preferences: ^2.5.2

  # JWT Decoder
  jwt_decoder: ^2.0.1

  # Settings UI
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/images/
