name: londri
description: "An application to manage laundry business"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  # Router
  go_router: ^14.8.0

  # Clean Architecture and BLoC
  flutter_bloc: ^9.0.0
  fpdart: ^1.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3

  # Supabase
  supabase_flutter: ^2.8.3

  # Dotenv
  flutter_dotenv: ^5.2.1

  # Google Fonts
  google_fonts: ^6.2.1

  # Localizations
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # UUID
  uuid: ^4.5.1

  # Shared Preferences
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/images/
